apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: gin-app-container # Changed container name
        image: go-app:latest # Keep image name for simplicity, build the Go app with this tag
        ports:
        - containerPort: 8080
